version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 4001:4000
    networks:
      - tasks

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - tasks


  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - tasks
    volumes:
      - mongo-data:/data/db

networks:
  tasks:
    driver: bridge

volumes:
  mongo-data:
    driver: local
